feature:BaseBallDBSetUp/#9
kybaq/3-feet pull request #11
Opened 2024-06-18 15:42 UTC by MinKonKim

## Description

### 구단 별로 {구단 아이디, 구단 명, 구단 로고 이미지, 구단 로고 배너, 위도, 경도} 형식으로 저장

## To-Do

- [x]  Club Table 생성 및 데이터 저장
- [x]  DB연결해서 데이터 받아오는지 확인
- [x] Club 데이터들을 전역으로 관리하기

## ETC
### 개발 내 추가 사항
- Supabase에 club db 추가
- club 데이터 가져오는 api 생성 ( 명세서에 추가 예정) : 추가 후 수정하겠습니다.
- club 데이터를 zustand 로 관리 가능함.
### 개발 외 추가 사항 
- HomePage 폴더 의 index.js 삭제 및 경로 수정
### **문제점**
- 구단 버튼을 클릭 후, 배너를 띄우기 까지 딜레이가 생김.
## up-to-date

###  2024.06.19

2024-06-18 19:52 UTC, hyeonseok98 requested changes
4:50분 기준 PR 테스트를 위해 실행 결과 오류가 뜨고 있습니다. 한 번 확인 부탁드릴게요!

※ 테스트 순서: 별도의 테스트 폴더 생성 →  git clone → npm i → supabase key, url 세팅 →11번 PR pull → npm run dev

2024-06-19 01:30 UTC, SecretCandy approved these changes

2024-06-19 02:17 UTC, hyeonseok98 approved these changes
테스트해서 확인 완료했습니다!! 고생 많으셨습니다

1. 첫 렌더링 이후 기본 구단 설정이 되어있지 않아, 에러가 발생합니다!
2. 생각보다 배너와 아래 넓이가 넓은 것 같아서 가로를 1080px로 작업해도 좋아보여요!

2024-06-19 02:18 UTC, kybaq approved these changes
동작하는 것 확인 했습니다! 수고하셨어요~!

2024-06-19 02:22 UTC, hyeonseok98 commented on src/components/HomePageComponents/Banner.jsx
> +      {banner !== 0 && (
banner !== 0은 null이나 undefined 같은 falsy한 값일때도 렌더링시켜서, banner로 사용해 falsy 값도 거르는 방법도 좋아보여요!

2024-06-19 02:28 UTC, merged